### ISSUE TITLE
Error when pretraining the DAMSM + CL ?

### ISSUE THREAD

**Issue by ghost** [huiyegit/T2I_CL#17]

**Comment by huiyegit** [comment]
It seems the data loader has some issue. You may check whether the read of dataset is correct.

**Comment by ghost** [comment]
Hello @huiyegit, thanks for your reply, I edited my comment it's in the DM-GAN+CL folder.

For the bird dataset, I downloaded from [here](https://www.vision.caltech.edu/datasets/cub_200_2011/) and follow the instructions for the dataset setup from the [DM-GAN](https://github.com/MinfengZhu/DM-GAN) repo, I don't know how to check if the data loader is correct when reading the dataset, can you help me, thank you !

**Comment by huiyegit** [comment]
You may trace the source code of reading data step by step, and check which step has the issue.

**Comment by ghost** [comment]
Do you know what kind of attention mechanism does the AttnGAN use ?

**Comment by huiyegit** [comment]
The attention of AttnGAN can be found here:  https://github.com/huiyegit/T2I_CL/blob/main/AttnGAN%2BCL/code/miscc/losses.py

**Comment by ghost** [comment]
Do you know what does the file GlobalAttention.py do ?

**Comment by huiyegit** [comment]
The foundation of Attention is in the GlobalAttention.py, which is also used in the losses.py.

**Comment by ghost** [comment]
The paper doesn't provide any information, so I don't know the specific types of Attention in the model.
