### ISSUE TITLE
Best DAMSM epoch ?

### ISSUE THREAD

**Issue by ghost** [huiyegit/T2I_CL#25]
Can anyone help me, I train the DAMSM for 600 epochs for bird dataset, how to know which epoch is the best for DAMSM to choose in order to train the GAN model, does anyone know ?

**Comment by huiyegit** [comment]
It should be the epoch 200. You may also try other checkpoints.

**Comment by ghost** [comment]
What do you mean try other checkpoints ?

What about `valid loss`, `s_loss`, `w_loss` outputs when I train the DAMSM, because after epoch 200, these stats seems decreasing should I choose based on these stats or something else ? Do you know ?

**Comment by huiyegit** [comment]
The metric for DAMSM may be the IS score, FID for the image quality.

**Comment by huiyegit** [comment]
> What do you mean try other checkpoints ?
> 
> What about `valid loss`, `s_loss`, `w_loss` outputs when I train the DAMSM, because after epoch 200, these stats seems decreasing should I choose based on these stats or something else ? Do you know ?

Checkpoints refer to the models saved at some epochs.

**Comment by huiyegit** [comment]
You are right. The feedback of DAMSM model is after the GAN training.
