### ISSUE TITLE
pretrained discriminator request

### ISSUE THREAD

**Issue by ts170** [huiyegit/T2I_CL#3]
Hello @huiyegit 
First of all, thank you for providing this code!
I am trying to utilize transfer learning (as in http://arxiv.org/pdf/1805.01677v2) to see if I can optimize the model for my test domain. As far as I understand, I would need a pretrained Discriminator as well to perform this task.
Unfortunately, due to hardware limitations, I am unable to perform the training myself with reasonable effort. This is why I wanted to ask if it would be possible for you to provide the discriminator model to go with the DM-GAN-CL COCO Generator with 200 Epochs and the AttnGAN-CL COCO Generator with 80 Epochs?

**Comment by huiyegit** [comment]
I only saved the Discriminators of the last epoch. Here are the links:
AttnGAN+CL, COCO, epoch 120:   https://drive.google.com/file/d/1-dMiXaoNVitAs6hQBSPLanLUEDkW5uUS/view?usp=sharing
DM-GAN+CL, COCO, epoch 200:  https://drive.google.com/file/d/1ObfV_5N9YA9PRNJFfh1Omn8TLS2Dn1D7/view?usp=sharing

**Comment by ts170** [comment]
Tanks a lot!
