### ISSUE TITLE
Throwing import error

### ISSUE THREAD

**Issue by Stelath** [huiyegit/T2I_CL#8]
I'm very sorry for posting such a simple bug but for the life of me I can't figure out why its throwing this error, I have tried reinstalling numpy and have all the required packages. Numpy even works when running other python files but not here for some reason.

Error:
```
Traceback (most recent call last):
  File "pretrain_DAMSM.py", line 3, in <module>
    from miscc.utils import mkdir_p
  File "/books-nn/T2I_CL/DM-GAN+CL/code/miscc/utils.py", line 4, in <module>
    from torch.nn import init
ModuleNotFoundError: No module named 'torch'
```

**Comment by Stelath** [comment]
This was thrown as a result of me running:
`sudo python2.7 pretrain_DAMSM.py --cfg cfg/DAMSM/book.yml --gpu 0`

**Comment by Stelath** [comment]
<img width="201" alt="Screen Shot 2021-12-08 at 9 08 08 PM" src="https://user-images.githubusercontent.com/25530613/145321386-cf8568e3-1e62-4e0f-ba89-14d41a3d9f22.png">

**Comment by huiyegit** [comment]
I think the problem is the environment. You'd better create an Anaconda virtual environment to install the required packages. Take it as a reference: https://github.com/huiyegit/APLC_XLNet

**Comment by Stelath** [comment]
It seems that switching from a python 3.7 conda environment to a python 3.6 conda environment solved the problem, thanks!
